AllCops:
  TargetRubyVersion: 3.1
Metrics/ParameterLists:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
